import type { MonacoTheme } from '../types/theme';

/**
 * GitHub Light theme — mirror of `github-dark` in palette inversion.
 * Matches GitHub's "light default" mode.
 */
export const githubLightTheme: MonacoTheme = {
  name: 'github-light',
  base: 'vs',
  inherit: true,
  rules: [
    { token: 'comment', foreground: '6e7781', fontStyle: 'italic' },
    { token: 'string', foreground: '0a3069' },
    { token: 'string.escape', foreground: '0550ae' },
    { token: 'constant', foreground: '0550ae' },
    { token: 'constant.numeric', foreground: '0550ae' },
    { token: 'constant.language', foreground: '0550ae' },
    { token: 'variable', foreground: '953800' },
    { token: 'variable.parameter', foreground: '953800' },
    { token: 'variable.other.constant', foreground: '0550ae' },
    { token: 'keyword', foreground: 'cf222e' },
    { token: 'keyword.control', foreground: 'cf222e' },
    { token: 'keyword.operator', foreground: 'cf222e' },
    { token: 'storage', foreground: 'cf222e' },
    { token: 'storage.type', foreground: 'cf222e' },
    { token: 'entity.name.function', foreground: '8250df' },
    { token: 'entity.name.class', foreground: '953800' },
    { token: 'entity.name.type', foreground: '953800' },
    { token: 'entity.name.tag', foreground: '116329' },
    { token: 'support.function', foreground: '8250df' },
    { token: 'support.class', foreground: '953800' },
    { token: 'support.type', foreground: '953800' },
    { token: 'punctuation.definition.tag', foreground: '116329' },
    { token: 'meta.tag', foreground: '24292f' },
    { token: 'invalid', foreground: '82071e', background: 'ffebe9' },
    { token: 'markup.heading', foreground: '0550ae', fontStyle: 'bold' },
    { token: 'markup.bold', foreground: '953800', fontStyle: 'bold' },
    { token: 'markup.italic', foreground: '0a3069', fontStyle: 'italic' },
    { token: 'markup.inserted', foreground: '116329', background: 'dafbe1' },
    { token: 'markup.deleted', foreground: '82071e', background: 'ffebe9' },
  ],
  colors: {
    'editor.background': '#ffffff',
    'editor.foreground': '#24292f',
    'editor.lineHighlightBackground': '#f6f8fa',
    'editor.selectionBackground': '#add6ff',
    'editor.inactiveSelectionBackground': '#e5e5e5',
    'editorCursor.foreground': '#24292f',
    'editorLineNumber.foreground': '#8c959f',
    'editorLineNumber.activeForeground': '#24292f',
    'editorIndentGuide.background': '#d8dee4',
    'editorIndentGuide.activeBackground': '#afb8c1',
    'editor.findMatchBackground': '#ffdf5d80',
    'editor.findMatchHighlightBackground': '#ffdf5d40',
    'editorBracketMatch.background': '#1a7f3722',
    'editorBracketMatch.border': '#1a7f3744',
    'editorGutter.modifiedBackground': '#bf8700',
    'editorGutter.addedBackground': '#1a7f37',
    'editorGutter.deletedBackground': '#cf222e',
    'diffEditor.insertedTextBackground': '#1a7f3722',
    'diffEditor.removedTextBackground': '#cf222e22',
  },
};
